const paypalPaymentNitificationMailActionType = {
    SEND_PAYPAL_PAYMENT_NOTIFICATION_MAIL_START: 'SEND_PAYPAL_PAYMENT_NOTIFICATION_MAIL_START',
    SEND_PAYPAL_PAYMENT_NOTIFICATION_MAIL_SUCCESS: 'SEND_PAYPAL_PAYMENT_NOTIFICATION_MAIL_SUCCESS',
    SEND_PAYPAL_PAYMENT_NOTIFICATION_MAIL_FAILURE: 'SEND_PAYPAL_PAYMENT_NOTIFICATION_MAIL_FAILURE'
}

export default paypalPaymentNitificationMailActionType;