const UserPurchaseListActionType = {
    GET_USER_PURCHASE_LIST_START : 'GET_USER_PURCHASE_LIST_START',
    GET_USER_PURCHASE_LIST_SUCCESS : 'GET_USER_PURCHASE_LIST_SUCCESS',
    GET_USER_PURCHASE_LIST_FAILURE : 'GET_USER_PURCHASE_LIST_FAILURE'
}

export default UserPurchaseListActionType;