const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    FETCH_COLLECTIONS_ITEM_DETAILS_START: 'FETCH_COLLECTIONS_ITEM_DETAILS_START',
    FETCH_COLLECTIONS_ITEM_DETAILS_SUCCESS: 'FETCH_COLLECTIONS_ITEM_DETAILS_SUCCESS',
    FETCH_COLLECTIONS_ITEM_DETAILS_FAILURE: 'FETCH_COLLECTIONS_ITEM_DETAILS_FAILURE',
    FETCH_COLLECTIONS_ITEM_DETAILS: 'FETCH_COLLECTIONS_ITEM_DETAILS',

}
export default ShopActionTypes;