const AdminActionTypes = {
    ADMIN_SIGN_IN_START : 'ADMIN_SIGN_IN_START',
    ADMIN_SIGN_IN_SUCCESS : 'ADMIN_SIGN_IN_SUCCESS',
    ADMIN_SIGN_IN_FAILURE : 'ADMIN_SIGN_IN_FAILURE',
    ADMIN_SIGN_OUT_START : 'ADMIN_SIGN_OUT_START',
    ADMIN_SIGN_OUT_SUCCESS : 'ADMIN_SIGN_OUT_SUCCESS',
    ADMIN_SIGN_OUT_FAILURE : 'ADMIN_SIGN_OUT_FAILURE'
}

export default AdminActionTypes;