const UserPurchaseActionType = {
    GET_USER_PURCHASE_START : 'GET_USER_PURCHASE_START',
    GET_USER_PURCHASE_SUCCESS : 'GET_USER_PURCHASE_SUCCESS',
    GET_USER_PURCHASE_FAILURE : 'GET_USER_PURCHASE_FAILURE',
}

export default UserPurchaseActionType;